### PR TITLE
Maven project

### PR DESCRIPTION
**Pull request by victorviola**
Project converted to Maven Project.

For developers:
0 - You should have Maven installed
1 - Clone this repository in your Visual Paradigm's plugin folder 
 
example in Windows - C:\Users\user_example\AppData\Roaming\VisualParadigm\plugins\

2 - Go to the plugin folder using your terminal and execute these two command in the following order:

i) **mvn initialize**

ii) **mvn compile**

You must execute maven initialize phase to ensure the installation of dependencies in your local maven repository. After the first execution you can ignore the initialize phase and execute just mvn clean compile / mvn compile.

### CODE REVIEW

**Comment by claudenirmf** [comment]
@victorviola, we need you to solve a couple of issues.

First, the compile phase is not working on my machine. In order to do that, I had to fix the  `maven-compiler-plugin` by replacing the configuration `<release>11</release>` for `<source>1.8</source><target>1.8</target>`. I am not sure, but I believe that this plugin enables `mvn` to import a set JVM enabling it to run even if the user doesn't have Java on its own machine. So it is necessary to make this change in order to guarantee that the plugin compiles the code to the desired java version (i.e., Java 8).

Second, I believe that the commands you are using a not standard. Check if you should change `mvn initialize` to `mvn install`, and `mvn compile` to `mvn build`.

Third, you must merge the `development` branch into your own and solve any conflicts before making a PR.

Fourth, we do not want JAR files within the project, you must refer to Visual Paradigm's own JAR files instead. In order to achieve that, please follow these steps:

- Create a `.env` file within the project with a variable like `VISUAL_PARADIGM_DEPENDENCIES=/Applications/Visual Paradigm.app/Contents/Resources`.
- Use this variable within `pom.xml` to declare all of the following dependencies:
  + /lib/vpplataform.jar
  + /lib/lib01.jar
  + /lib/lib02.jar
  + /lib/lib03.jar
  + /lib/lib04.jar
  + /lib/lib05.jar
  + /lib/lib06.jar
  + /lib/lib07.jar
  + /lib/lib09.jar
  + /lib/openapi.jar
  + /lib/jniwrap.jar
  + /lib/winpack.jar
  + /ormlib/orm.jar

Every developer will need to update `VISUAL_PARADIGM_DEPENDENCIES` according its own installation of Visual Paradigm before running `mvn`. As a consequence, changes to `.env` must not be committed to the repository.

Fifth, clean the project of any unnecessary files and folders, such as `/target`. Also, clean `.gitignore` of any unnecessary declarations and include Eclipse specific files to the ignored list (e.g., `.settings` and `.classpath`).

I believe this is all, but double-check. I guess that other minor fixes should be worked out on our next Trello feature card.

**Comment by claudenirmf** [comment]
Just adding two things. You can check the dependencies I have requested you to include [here](https://knowhow.visual-paradigm.com/openapi/debug-plugins-eclipse/). Also, I have tried your PR on Ubuntu and it works there as well, given that the Java versioning issue is solved.

**Comment by victorviola** [comment]
Hi, here are my comments regarding the topics you mentioned:

First
Marked as solved according to your second comment in this pull request.

Second

> Check if you should change mvn initialize to mvn install

In my understanding this is a normal proceeding in this specific case.
Assumptions:
- According to the maven lifecycle when you execute a given phase all the prior phases are executed before the one you selected.
- install-file goal is declared in the initialize phase (could be in another like validate)
- maven initialize phase comes before compile phase 

So if we follow the logic presented above we should only need to execute mvn compile phase and everything should run. This is not true for the specific project we have here. We have a dependency that is not installed in any repository (local or remote) and before maven starts compile phase it will resolve all the dependency tree prior to start building.
Dependency tree is resolved before start building. That is  why it fails in the very first attempt even though maven initialize phase is before to compile. This is the reason we need to explicit call for maven initialize phase.

> and mvn compile to mvn build.

I guess there is no phase called build in maven. Compile phase is the one we need and no other after in the lifecycle.


Third
The only conflict we have now is in the gitignore file. Added more files and folders. I may suggest to keep my version.

Fourth
If we choose this approach we have two ways to achieve this:

1 - declare the dependecy pointing to the local file system

<dependency>
    <groupId>com.sample</groupId>
    <artifactId>sample</artifactId>
    <version>1.0</version>
    <scope>system</scope>
    <systemPath>${PATH_DECLARED_IN_ENV_FILE}/VISUAL_PARADIGM.jar</systemPath>
</dependency>

2 - use install plugin/install-file goal as we are currently doing but instead of pointing to the jar inside the project we are going to use the 
path declared in the env file. 

Number 1 I guess is deprecated.
Number 2 will need maven initialize as I pointed above. 

And In my opinion I prefer to keep the local jars INSIDE the project so we can guarantee that the code we are doing is related to that specific jar.

Can we please discuss more about this Fourth point?

Fifth
Done.

**Comment by tgoprince** [comment]
Please add the zip generation phase and the instructions on the README.md file.

**Comment by claudenirmf** [comment]
Guys, I have changed a couple of things in the POM file.

I have set up a variable to track the installation folder of Visual Paradigm, which is necessary for the project to get all local development dependencies. Everything is stored locally within the `~/.m2` folder, alongside GSON, for example.

If you, as a developer, are running your project on a Linux or Windows machine, you should update this variable by informing your installation path in the command line:
```shell
mvn -Dvisualparadigm.app.dir=/Applications/Visual\ Paradigm.app/Contents/Resources/app/ initialize
mvn -Dvisualparadigm.app.dir=/Applications/Visual\ Paradigm.app/Contents/Resources/app/ compile
```

I failed to put the variable `visualparadigm.app.dir` outside the POM file, no matter what I've tried.

After all of this, I manually generated a ZIP file out of the project (including the compiled classes) and it worked fine in Ubuntu, even though *THERE WAS NO GSON* jar in the system. I don't know why it works without GSON. It looks like the compiled file have all necessary code.

So, are we able to close this for now?

**Comment by victorviola** [comment]
- added Readme.md
- added generation of the zip file
- improved maven clean phase to remove .zip file


> So, are we able to merge this for now?
I agree to proceed.

**Pull request merged**
