### PR TITLE
Plugin Update Automation

### LINKED ISSUE #60: Automatic Update Feature
Evolve the "Update Plugin" feature to automatically check and download releases from the GitHub repository.

Allow users to opt-in beta releases.

Keep manual updates from downloaded files to enable rollbacks.

### PR DESCRIPTION
**Pull request by claudenirmf**
Enables automatic plugin update from GitHub releases

closes #60

### CODE REVIEW

**Comment by claudenirmf** [comment]
Plugin version selection:

Screenshot 2020-08-06 at 22 27 01

Screenshot 2020-08-06 at 22 26 40

This is not the main window. The main window shall have the buttons "Install Latest Release", "Select a Release", or "Cancel".

**Comment by claudenirmf** [comment]
The plugin was tested on both Windows 10 and Linux and seems to be working as expected.

The automatic lookup for new updates runs daily just after some project is opened. Whether or not there are newer stable releases available, a message appears in the bottom log for the user (for testing, the 24 hours "cooldown" was reduced to 1 second, so just open any project to see the message).

If you do install another version through the UI, beware that running `mvn install` may add a second plugin to the plugins folder, raising error messages and preventing the plugin from being properly loaded. This is not an issue if don't use `mvn install` because the plugin removes any folder containing `"ontouml-vp-plugin"` in its names leaving only the desired installation.

**Comment by claudenirmf** [comment]
Ready for review

**Comment by claudenirmf** [comment]
I believe it is ready to merge.

I took the opportunity to do some refactoring.

I won't go into further changes in this PR.

**Review by tgoprince — APPROVED** [review]

**Pull request merged**
