### PR TITLE
Release 0.5.2

### LINKED ISSUE #105: Derivations serialized as relations without stereotype
Plugin version: 0.5.1

Visual Paradigm does not support relations connected to other relations.
So, to represent derivation relations, we use association classes.

These should be serialized as derivation relations, in which the truthmaker (the class) is the source and the relation is the target. Currently, these association classes are serialized as plain relations without any stereotype, causing other features to break (e.g. the transformation from OntoUML to gUFO).

### LINKED ISSUE #106: Base IRI ignored in the transformation from OntoUML to gUFO
Plugin version 0.5.1

In the transformation from OntoUML to gUFO, the Base IRI parameter is being ignored.
The resulting ttl file always includes http://example.com as the base IRI.

### PR DESCRIPTION
**Pull request by claudenirmf**
Fixes versioning issues on association direction and aggregation kind.
Fixes #105 
Fixes #106

### CODE REVIEW

**Comment by tgoprince** [comment]
> Fixes versioning issues on association direction and aggregation kind.

Could tell me how I test this bugfix?

**Comment by tgoprince** [comment]
Can we add unit tests for #105?

**Comment by claudenirmf** [comment]
> Could tell me how I test this bugfix?

The current release does not work on VP 16.3 onwards. On the new VP version, aggregations and navigability arrows are not set when changing the stereotype, and inverting associations do not work.

The fix, however, does not work on VP 16.2 and older.

Testing must be done manually by adding stereotypes to associations as well as inverting them, verifying if aggregations and navigability are properly set. Tests must be perform on VP 16.3 or newer.

**Comment by claudenirmf** [comment]
> Can we add unit tests for #105?

We can't have unit tests because all changes were made to the loader and the transformer. These bits require VP to be running to perform tests. Manual testing was performing by exporting models including derivations to JSON and gUFO and later importing the JSON ones.

**Pull request merged**
