### PR TITLE
OntoUML Schema generation and error display on log panel

### PR DESCRIPTION
**Pull request by claudenirmf**
This merge adds the following features:

- OntoUML Schema model generation
- Remote model verification
- Errors displayed on log panel.
- For now, the generated OntoUML Schema model is copied to the clipboard, allowing easy access during debugging.

Transformation shall be updated to work around the limitations of GSON's serialization and improvements on OntoUML Schema.

### CODE REVIEW

**Comment by victorviola** [comment]
Olá, @claudenirmf.
Tentei executar o projeto mas recebo uma exception na linha 115 do file ValidateOntoUMLModel.java.

`Package newPackage = new Package((IPackage) projectElement);`

>  java.lang.ClassCastException: class v.ben.buq cannot be cast to class com.vp.plugin.model.IPackage (v.ben.buq and com.vp.plugin.model.IPackage

Para realizar esse cast, não deveria a classe Package e demais structuralElements serem implementações de IModelElement?

**Comment by claudenirmf** [comment]
Can you please share the model you used? I guess that I tried to cast some incompatible `IModelElement` to `IPackage`.

About your suggestion, I changed a bit the approach in should a way that every implementation 
`StructuralElement` keeps a reference to the IModelElement it is based on. That way it easy to get whatever information you need without having to update that `HashMap<Id,StructuralElement>`. For that, I require the original (a.k.a. source) `IModelElement` to be passed to the constructor.

**Comment by victorviola** [comment]
Ok. I got it now. When I implemented the classes that represents the whole schema the idea was to have those classes reusable in the future for other kind of projects.

The model I tested in VP you can find in the following folder of the project (vpp projects/TestModel.vpp)

**Comment by claudenirmf** [comment]
I believe I have corrected the issue, but I was not able to test your model because you use a newer version of VP. Maybe we should share models in XMI to avoid version issues.

I also took the opportunity to fix an issue I was having with GSON's serialization with empty arrays (which is not allowed by OntoUML Schema). Now, class attributes are also sent to the server and non- standard stereotypes are not ignored.

**Comment by claudenirmf** [comment]
Many developments were executed on a different branch (#dev-config-menu), including improvements to this one.

This request will be closed to avoid possible conflicts.

**Pull request closed without merging**
