### PR TITLE
New UI to access the ontouml2gufo service

### PR DESCRIPTION
**Pull request by victorviola**
This PR intends to solve the following issues:

ontouml2gufo - model selection for transformation [22](https://github.com/OntoUML/ontouml-vp-plugin/issues/22)
UI for the ontouml2gufo transformation [25](https://github.com/OntoUML/ontouml-vp-plugin/issues/25)
Add progress bar when interacting with the OntoUML sever [31](https://github.com/OntoUML/ontouml-vp-plugin/issues/31)
Persist user parameters for GUFO transformation [40](https://github.com/OntoUML/ontouml-vp-plugin/issues/40)

Example in windows:

image

### CODE REVIEW

**Comment by claudenirmf** [comment]
@victorviola, did I tell you that the menu made is beautiful? Because it is =)

**Comment by victorviola** [comment]
Many thanks @claudenirmf

Thank you for your support throughout the project.

:)

**Comment by claudenirmf** [comment]
I have updated the code which is now performing **Smart Modeling** and automatically propagating the values of `restrictedTo` to specializations of sortals while enforcing its default value on classes where it is fixed.

Non-sortals do not propagate their value of `restrictedTo` to subclasses nor get its value from superclasses. Here the user needs to inform the proper value, while the default is `functional-complex`.

The default value of `restrictedTo` to «subkind», «role»,«phase», and «historicalRole» is `""` (i.e., empty/none).

Classes decorated as «historicalRole» are automatically updated if the specialize some sortal class, in which case it will include its value of `restrictedTo`. Otherwise, its value must be defined by the user.

The set of property change events that trigger the update of `restrictedTo` and Smart Coloring was reduced to a minimum.

The access and manipulation of stereotypes and tagged values were updated.

The algorithm to install stereotypes was updated to prevent duplication of "hidden" tagged values in classes.

The plugin was tested by the development of a number of consistent and inconsistent OntoUML ontologies.

**Comment by claudenirmf** [comment]
Ok, «historicalRole» is a really annoying case for inference. Since there is no «historicalRoleMixin», I forced to:

 - Leave «historicalRole» as user-defined, no inference of `restrictedTo`
 - Sortal classes inherit the value `restritedTo` from «historicalRole»

**Comment by claudenirmf** [comment]
Just passing to share the color scheme I am incorporating now, which gives emphasis to ultimate sortal («kind», «collective», «quantity», «relator», «mode», «quality»).

Screenshot 2020-06-23 at 08 10 37

A nice thing about the color scheme we are using is that it seems to be friendly to most types of colorblindness =)

Screenshot 2020-06-23 at 07 52 46

Screenshot 2020-06-23 at 07 53 16

Screenshot 2020-06-23 at 07 53 21

**Comment by claudenirmf** [comment]
Re-ordered/re-grouped menus:

Screenshot 2020-06-23 at 09 14 32

Screenshot 2020-06-23 at 09 14 15

Screenshot 2020-06-23 at 09 13 28

**Comment by claudenirmf** [comment]
Oh, I've noticed we can disable some options in this dialog when Smart Modeling is enabled. This is because in this situation, you can only change the restrictions of non-sortals and they can have none of those disabled options.

Screenshot 2020-07-02 at 02 39 58

**Pull request merged**
