### PR TITLE
New feature: Import/Export diagrams

### PR DESCRIPTION
**Pull request by tgoprince**
This PR adds a feature to the plugin that allows exporting the diagrams of a project in addition to the model.

It also allows users to import model and diagrams from a JSON file.

In order to implement these features and improve the maintainability of the project, the de/serialization was re-implemented using Jackson instead of GSON and separating the transformation from VP instances to OntoUML instances from the serialization.

I also added tests for the serialization and deserialization modules.

These new features allow us to consume the new complexity management service that we have just developed, which generates views of the model following a relation-based strategy.  

TODOs: 
- Add a menu option to access the complexity management service
- Delete classes related to the previous serialization strategy
- Make the ontouml2gufo controller request the new serialization

### CODE REVIEW

**Review by claudenirmf — CHANGES_REQUESTED** [review]
I have added the field "value" to the serialization of shapes with type "Text", otherwise the serialization would not be compatible with the updated JSON Schemas. Still, there are a couple of things to fix and maybe you could do it

 - Package views are not serialized, so they break the serialization when present in diagrams.
 - Diagrams cannot be serialized separately yet, so the verification of diagrams is not working.
 - The deserialization reconstructs all diagrams, deleting diagram elements that cannot be serialized. We need a deserialization of diagrams that does not override those that already exist.

The test server is running at [http://api.ontouml.org:3001](http://api.ontouml.org:3001), and I have updated the default link on this branch to match it.

I'll continue the refactoring on the service requests to update the dialogs and do some refactoring.

**Comment by tgoprince** [comment]
This last commit fixes two things:

1. Importing projects and running the modularization services does not override existing diagrams anymore. 
2. Diagrams generated by the modularization services are automatically organized by the auto-layout feature embedded in Visual Paradigm.

**Comment by tgoprince** [comment]
Commit 5d28695 fixes the bug related to the improper serialization of package views, as well as adds support for deserializing package views.

**Comment by claudenirmf** [comment]
With the latest commit, I have refactored services: Model/Diagram Verification, JSON Import/Export, and gUFO Export. I have not, however, tried to remove Gson from the project yet and I don't see this as a priority for this PR.

There are still two known issues: (i) serialization of inverted derivation relations break the process; and (ii) the selection tree in the gUFO export is ignored since we can't partially serialize projects at the moment. For (ii) I suggest keeping the interface and locking the selection tree.

I hope that we can make a new release after addressing this 2 issues. Please test it and consider releasing it as version 0.5.0.

**Comment by claudenirmf** [comment]
Btw, I have noticed that in this PR we have intrinsic modes in blue, extrinsic modes in green, and modes that are both in grey. Haven't we talked about changing this? I cannot find our decision among my notes.

**Comment by claudenirmf** [comment]
> There are still two known issues: (i) serialization of inverted derivation relations break the process; and (ii) the selection tree in the gUFO export is ignored since we can't partially serialize projects at the moment. For (ii) I suggest keeping the interface and locking the selection tree.

(i) The class Trace was updated with null-safe methods to avoid breaking the serialization of inverted derivation relations.

(ii) It was decided that the "Export to gUFO" interface will have a locked model element/diagram selection for the moment. A new issue will be created to support the partial serialization of projects and re-enable selection in this export interface.

> Btw, I have noticed that in this PR we have intrinsic modes in blue, extrinsic modes in green, and modes that are both in grey. Haven't we talked about changing this? I cannot find our decision among my notes.

It was decided that all modes should be paint in blue to avoid inconsistencies in some diagrams.

**Review by claudenirmf — APPROVED** [review]

**Pull request merged**
